### ISSUE TITLE
Installation failure with ruby-2.4.0

### ISSUE THREAD

**Issue by masutaka** [erniebrodeur/pushover#23]
Thank you for your great gem!

I can't install it with ruby-2.4.0. I believe it needs to bump yajl-ruby to 1.3.0. See https://github.com/brianmario/yajl-ruby/pull/165

```
current directory: /Users/masutaka/src/github.com/masutaka/dotfiles/vendor/bundle/gems/yajl-ruby-1.1.0/ext/yajl
/Users/masutaka/.rbenv/versions/2.4.0/bin/ruby -r ./siteconf20161231-77571-1bi4alv.rb extconf.rb
creating Makefile

current directory: /Users/masutaka/src/github.com/masutaka/dotfiles/vendor/bundle/gems/yajl-ruby-1.1.0/ext/yajl
make "DESTDIR=" clean

current directory: /Users/masutaka/src/github.com/masutaka/dotfiles/vendor/bundle/gems/yajl-ruby-1.1.0/ext/yajl
make "DESTDIR="
compiling yajl.c
compiling yajl_alloc.c
compiling yajl_buf.c
compiling yajl_encode.c
compiling yajl_ext.c
yajl_ext.c:852:22: error: use of undeclared identifier 'rb_cFixnum'
    rb_define_method(rb_cFixnum, "to_json", rb_yajl_json_ext_fixnum_to_json, -1);
                     ^
1 error generated.
make: *** [yajl_ext.o] Error 1

make failed, exit code 2
```

**Comment by ConfusedVorlon** [comment]
+1
thank you.

**Comment by ConfusedVorlon** [comment]
btw: looks like this is something you are addressing in the feature-rewrite branch. 
I have tried working from that. Bundle install now works,  but I get an error when running tests or the server.

this seems to be related to rspec. I'm not using rspec myself - but I have tried adding rspec to my gemfile for development/test. I also did an `rspec --init` That doesn't make a difference.

```
/Users/rob/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- spec_helper (LoadError)
	from /Users/rob/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/rob/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/rob/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/rob/.rvm/gems/ruby-2.4.0/bundler/gems/pushover-3ffe8218f164/lib/pushover/api.rb:1:in `<top (required)>'
	from /Users/rob/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/rob/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/rob/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/rob/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/rob/.rvm/gems/ruby-2.4.0/bundler/gems/pushover-3ffe8218f164/lib/pushover.rb:2:in `<top (required)>'
```

**Comment by erniebrodeur** [comment]
Hi, yeah, this is the major reason I'm doing this.   Getting everything upto date.  

I've suddenly had quite a few more users since aws started using pushover.

It's going to take me a bit of time, the rewrite will take several weeks as I only work on it in my spare time.

I'll spend some time this weekend making sure the old version can run on the newest ruby.

**Comment by ConfusedVorlon** [comment]
thank you!

**Comment by steigr** [comment]
Are you still refactoring or need help?

**Comment by edwardmp** [comment]
@erniebrodeur 
Do you need some help?
